services:
  balancer:
    image: 'nginx'
    container_name: nginx-balancer
    volumes:
      - ./nginx/:/etc/nginx:ro
    ports:
      - '80:80'
    networks:
      - default

  node1:
    image: 'iaw/worker:1.0'
    hostname: 'node1'
    expose:
      - '3000'
    ports:
      - '3001:3000'
    networks:
      - default

  node2:
    image: 'iaw/worker:1.0'
    hostname: 'node2'
    expose:
      - '3000'
    ports:
      - '3002:3000'
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Floorplan-Management-System
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - default

networks:
  default:
    driver: bridge
