export enum TipoDestino {
  VIVIENDA_UNIFAMILIAR = 'VIVIENDA UNIFAMILIAR',
  VIVIENDA_MULTIFAMILIAR = 'VIVIENDA MULTIFAMILIAR',
  VIVIENDA_UNIFAMILIAR_AGRUPADA = 'VIVIENDA UNIFAMILIAR AGRUPADA',
  OFICINA = 'OFICINA',
  LOCAL_COMERCIAL = 'LOCAL COMERCIAL',
  INDUSTRIA = 'INDUSTRIA',
}
